/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import model.Sistema;
import model.Entrada;
import model.Salida;
import model.ServicioAdicional;
import model.Vehiculo;

public class VentanaReportes extends javax.swing.JFrame {

    private Sistema sistema;
    private ArrayList<Object> movimientosActuales;
    private String matricula;
    private javax.swing.ButtonGroup buttonGroupOrdenamiento;

    public VentanaReportes(Sistema sistema) {  
        this.sistema = sistema;

        initComponents();
        
        // Crear ButtonGroup para los radio buttons
        buttonGroupOrdenamiento = new javax.swing.ButtonGroup();
        buttonGroupOrdenamiento.add(jRadioButtonFechaHoraCreciente);
        buttonGroupOrdenamiento.add(jRadioButtonFechaHoraDecreciente);
        
        iniciarTabla();
        actualizarListaVehiculos();
        
        jCheckBoxEntradas.setSelected(true);
        jCheckBoxSalidas.setSelected(true);
        jCheckBoxServicios.setSelected(true);
        jRadioButtonFechaHoraCreciente.setSelected(true);

        ClaroOscuro.aplicarModo(this);
        
        //Listener para la Lista
        jListVehiculos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    mostrarVehiculoSeleccionado();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelReportes = new javax.swing.JPanel();
        jTabbedPaneReportes = new javax.swing.JTabbedPane();
        jPanelHistorial = new javax.swing.JPanel();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        jListVehiculos = new javax.swing.JList<>();
        jLabelListaDeVehiculos = new javax.swing.JLabel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabelFiltrar = new javax.swing.JLabel();
        jCheckBoxEntradas = new javax.swing.JCheckBox();
        jCheckBoxSalidas = new javax.swing.JCheckBox();
        jCheckBoxServicios = new javax.swing.JCheckBox();
        jButtonExportar = new javax.swing.JButton();
        jLabelMovimientosDelVehiculo = new javax.swing.JLabel();
        jRadioButtonFechaHoraCreciente = new javax.swing.JRadioButton();
        jRadioButtonFechaHoraDecreciente = new javax.swing.JRadioButton();
        jPanelEstadisticas = new javax.swing.JPanel();
        jLabelServiciosMasUtilizados = new javax.swing.JLabel();
        jScrollPaneServiciosMasUtilizados = new javax.swing.JScrollPane();
        jListServiciosMasUtilizados = new javax.swing.JList<>();
        jLabelEmpleadosConMenosMovimientos = new javax.swing.JLabel();
        jScrollPaneEmpleadosConMenosMovimientos = new javax.swing.JScrollPane();
        jListEmpleadosConMenosMovimientos = new javax.swing.JList<>();
        jLabelEstadiaMasLarga = new javax.swing.JLabel();
        jLabelClientesConMasVehiculos = new javax.swing.JLabel();
        jScrollPaneClientesConMasVehiculos = new javax.swing.JScrollPane();
        jListClientesConMasVehiculos = new javax.swing.JList<>();
        jLabelEstadia = new javax.swing.JLabel();
        jPanelMovimientos = new javax.swing.JPanel();
        jLabelSeleccionFecha = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jPanelBotones = new javax.swing.JPanel();
        jButtonHora1Dia1 = new javax.swing.JButton();
        jButtonHora1Dia2 = new javax.swing.JButton();
        jButtonHora1Dia3 = new javax.swing.JButton();
        jButtonHora2Dia1 = new javax.swing.JButton();
        jButtonHora2Dia2 = new javax.swing.JButton();
        jButtonHora2Dia3 = new javax.swing.JButton();
        jButtonHora3Dia1 = new javax.swing.JButton();
        jButtonHora3Dia2 = new javax.swing.JButton();
        jButtonHora3Dia3 = new javax.swing.JButton();
        jButtonHora4Dia1 = new javax.swing.JButton();
        jButtonHora4Dia2 = new javax.swing.JButton();
        jButtonHora4Dia3 = new javax.swing.JButton();
        jLabelHora18a00 = new javax.swing.JLabel();
        jLabelDia3 = new javax.swing.JLabel();
        jLabelDia2 = new javax.swing.JLabel();
        jLabelDia1 = new javax.swing.JLabel();
        jLabelHora0a6 = new javax.swing.JLabel();
        jLabelHora6a12 = new javax.swing.JLabel();
        jLabelHora12a18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        getContentPane().setLayout(null);

        jPanelReportes.setLayout(null);

        jPanelHistorial.setLayout(null);

        jListVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneVehiculos.setViewportView(jListVehiculos);

        jPanelHistorial.add(jScrollPaneVehiculos);
        jScrollPaneVehiculos.setBounds(30, 50, 100, 170);

        jLabelListaDeVehiculos.setText("Lista de vehículos:");
        jPanelHistorial.add(jLabelListaDeVehiculos);
        jLabelListaDeVehiculos.setBounds(30, 20, 120, 16);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTable.setViewportView(jTable);

        jPanelHistorial.add(jScrollPaneTable);
        jScrollPaneTable.setBounds(160, 50, 320, 170);

        jLabelFiltrar.setText("Filtrar:");
        jPanelHistorial.add(jLabelFiltrar);
        jLabelFiltrar.setBounds(500, 20, 80, 16);

        jCheckBoxEntradas.setText("Entradas");
        jCheckBoxEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEntradasActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jCheckBoxEntradas);
        jCheckBoxEntradas.setBounds(500, 50, 90, 20);

        jCheckBoxSalidas.setText("Salidas");
        jCheckBoxSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSalidasActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jCheckBoxSalidas);
        jCheckBoxSalidas.setBounds(500, 80, 90, 20);

        jCheckBoxServicios.setText("Servicios");
        jCheckBoxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxServiciosActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jCheckBoxServicios);
        jCheckBoxServicios.setBounds(500, 110, 90, 20);

        jButtonExportar.setText("Exportar");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jButtonExportar);
        jButtonExportar.setBounds(500, 187, 90, 30);

        jLabelMovimientosDelVehiculo.setText("Movimientos del vehículo:");
        jPanelHistorial.add(jLabelMovimientosDelVehiculo);
        jLabelMovimientosDelVehiculo.setBounds(160, 20, 210, 16);

        jRadioButtonFechaHoraCreciente.setText("Fecha/Hora Creciente");
        jRadioButtonFechaHoraCreciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFechaHoraCrecienteActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jRadioButtonFechaHoraCreciente);
        jRadioButtonFechaHoraCreciente.setBounds(160, 230, 150, 21);

        jRadioButtonFechaHoraDecreciente.setText("Fecha/Hora Decreciente");
        jRadioButtonFechaHoraDecreciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFechaHoraDecrecienteActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jRadioButtonFechaHoraDecreciente);
        jRadioButtonFechaHoraDecreciente.setBounds(320, 230, 160, 21);

        jTabbedPaneReportes.addTab("Historial", jPanelHistorial);

        jPanelEstadisticas.setLayout(null);

        jLabelServiciosMasUtilizados.setText("Servicios más utilizados:");
        jPanelEstadisticas.add(jLabelServiciosMasUtilizados);
        jLabelServiciosMasUtilizados.setBounds(0, 40, 150, 16);

        jListServiciosMasUtilizados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneServiciosMasUtilizados.setViewportView(jListServiciosMasUtilizados);

        jPanelEstadisticas.add(jScrollPaneServiciosMasUtilizados);
        jScrollPaneServiciosMasUtilizados.setBounds(0, 60, 120, 100);

        jLabelEmpleadosConMenosMovimientos.setText("Empleados con menos movimientos:");
        jPanelEstadisticas.add(jLabelEmpleadosConMenosMovimientos);
        jLabelEmpleadosConMenosMovimientos.setBounds(160, 40, 210, 16);

        jListEmpleadosConMenosMovimientos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleadosConMenosMovimientos.setViewportView(jListEmpleadosConMenosMovimientos);

        jPanelEstadisticas.add(jScrollPaneEmpleadosConMenosMovimientos);
        jScrollPaneEmpleadosConMenosMovimientos.setBounds(160, 60, 120, 100);

        jLabelEstadiaMasLarga.setText("Estadía más larga:");
        jPanelEstadisticas.add(jLabelEstadiaMasLarga);
        jLabelEstadiaMasLarga.setBounds(0, 180, 110, 16);

        jLabelClientesConMasVehiculos.setText("Clientes con más vehículos:");
        jPanelEstadisticas.add(jLabelClientesConMasVehiculos);
        jLabelClientesConMasVehiculos.setBounds(400, 40, 150, 16);

        jListClientesConMasVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneClientesConMasVehiculos.setViewportView(jListClientesConMasVehiculos);

        jPanelEstadisticas.add(jScrollPaneClientesConMasVehiculos);
        jScrollPaneClientesConMasVehiculos.setBounds(400, 60, 120, 100);

        jLabelEstadia.setText("Ninguna estadía");
        jPanelEstadisticas.add(jLabelEstadia);
        jLabelEstadia.setBounds(110, 180, 100, 16);

        jTabbedPaneReportes.addTab("Estadísticas Generales", jPanelEstadisticas);

        jPanelMovimientos.setLayout(null);

        jLabelSeleccionFecha.setText("Selección fecha:");
        jPanelMovimientos.add(jLabelSeleccionFecha);
        jLabelSeleccionFecha.setBounds(20, 20, 100, 16);

        jButtonActualizar.setText("Actualizar");
        jPanelMovimientos.add(jButtonActualizar);
        jButtonActualizar.setBounds(210, 20, 100, 27);
        jPanelMovimientos.add(jTextFieldFecha);
        jTextFieldFecha.setBounds(120, 20, 75, 26);

        jPanelBotones.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        jButtonHora1Dia1.setText("Hora 1 - Dia 1");
        jPanelBotones.add(jButtonHora1Dia1);

        jButtonHora1Dia2.setText("Hora 1 - Dia 2");
        jPanelBotones.add(jButtonHora1Dia2);

        jButtonHora1Dia3.setText("Hora 1 - Dia 3");
        jPanelBotones.add(jButtonHora1Dia3);

        jButtonHora2Dia1.setText("Hora 2 - Dia 1");
        jPanelBotones.add(jButtonHora2Dia1);

        jButtonHora2Dia2.setText("Hora 2 - Dia 2");
        jPanelBotones.add(jButtonHora2Dia2);

        jButtonHora2Dia3.setText("Hora 2 - Dia 3");
        jPanelBotones.add(jButtonHora2Dia3);

        jButtonHora3Dia1.setText("Hora 3 - Dia 1");
        jPanelBotones.add(jButtonHora3Dia1);

        jButtonHora3Dia2.setText("Hora 3 - Dia 2");
        jPanelBotones.add(jButtonHora3Dia2);

        jButtonHora3Dia3.setText("Hora 3 - Dia 3");
        jPanelBotones.add(jButtonHora3Dia3);

        jButtonHora4Dia1.setText("Hora 4 - Dia 1");
        jPanelBotones.add(jButtonHora4Dia1);

        jButtonHora4Dia2.setText("Hora 4 - Dia 2");
        jPanelBotones.add(jButtonHora4Dia2);

        jButtonHora4Dia3.setText("Hora 4 - Dia 3");
        jPanelBotones.add(jButtonHora4Dia3);

        jPanelMovimientos.add(jPanelBotones);
        jPanelBotones.setBounds(90, 90, 430, 160);

        jLabelHora18a00.setText("18:00-23:59");
        jPanelMovimientos.add(jLabelHora18a00);
        jLabelHora18a00.setBounds(10, 220, 80, 16);

        jLabelDia3.setText("Día 3");
        jPanelMovimientos.add(jLabelDia3);
        jLabelDia3.setBounds(430, 60, 140, 16);

        jLabelDia2.setText("Día 2");
        jPanelMovimientos.add(jLabelDia2);
        jLabelDia2.setBounds(290, 60, 140, 16);

        jLabelDia1.setText("Día 1");
        jPanelMovimientos.add(jLabelDia1);
        jLabelDia1.setBounds(140, 60, 140, 16);

        jLabelHora0a6.setText("00:00-05:59");
        jPanelMovimientos.add(jLabelHora0a6);
        jLabelHora0a6.setBounds(10, 100, 80, 16);

        jLabelHora6a12.setText("06:00-11:59");
        jPanelMovimientos.add(jLabelHora6a12);
        jLabelHora6a12.setBounds(10, 140, 80, 16);

        jLabelHora12a18.setText("12:00-17:59");
        jPanelMovimientos.add(jLabelHora12a18);
        jLabelHora12a18.setBounds(10, 180, 80, 16);

        jTabbedPaneReportes.addTab("Movimientos", jPanelMovimientos);

        jPanelReportes.add(jTabbedPaneReportes);
        jTabbedPaneReportes.setBounds(40, 50, 610, 300);

        getContentPane().add(jPanelReportes);
        jPanelReportes.setBounds(0, 0, 650, 350);

        setBounds(0, 0, 663, 378);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarTabla(){
        String[] columnas = {"Tipo", "Fecha", "Hora", "Detalles"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // esto hace que la table no se pueda editar
            }
        };
        jTable.setModel(modelo);
        
    }
    
    private void actualizarListaVehiculos() {
        ArrayList<Vehiculo> vehiculos = sistema.getListaVehiculos();
        DefaultListModel<String> modelo = new DefaultListModel<>();

        for (int i = 0; i < vehiculos.size(); i++) {
            Vehiculo vehiculo = vehiculos.get(i);
            modelo.addElement(vehiculo.getMarca() + " " + vehiculo.getModelo() + " - " + vehiculo.getMatricula());
        }

        jListVehiculos.setModel(modelo);
    }
    
    public void mostrarVehiculoSeleccionado(){
        String seleccionado = jListVehiculos.getSelectedValue();
        
        if (seleccionado != null) {
            try {
                matricula = seleccionado.split(" - ")[1];
                actualizarTabla();
            } catch (Exception e) {
                ClaroOscuro.mostrarError(this, "Error al cargar datos del vehiculo: " + e.getMessage(), "Error");
            }
        }
    }
    
    public void actualizarTabla(){
        ArrayList<Object> movimientos = sistema.getMovimientosVehiculo(matricula);
        
        // Fitrar
        boolean entradas = jCheckBoxEntradas.isSelected();
        boolean salidas = jCheckBoxSalidas.isSelected();
        boolean servicios = jCheckBoxServicios.isSelected();
        movimientos = sistema.filtrarMovimientos(movimientos, entradas, salidas, servicios);
        
        //Ordenar
        boolean ascendente = jRadioButtonFechaHoraCreciente.isSelected();
        movimientos = sistema.ordenarMovimientos(movimientos, ascendente);
        
        // Guarda movimientos para exportar
        this.movimientosActuales = movimientos;
        
        //Actualiza la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
        modelo.setRowCount(0); // esto limpia la tabla
        
        for (int i = 0; i < movimientos.size(); i++) {
            Object movimiento = movimientos.get(i);
            
            String tipo = "";
            String fecha = "";
            String hora = "";
            String detalles = "";
            
            if (movimiento instanceof Entrada) {
                Entrada entrada = (Entrada) movimiento;
                tipo = "ENTRADA";
                fecha = entrada.getFecha();
                hora = entrada.getHora();
                detalles = "Empleado: " + entrada.getEmpleado().getNombre();
                if (!entrada.getNota().isEmpty()) {
                    detalles += " - Notas: " + entrada.getNota();
                }
            } else if (movimiento instanceof Salida) {
                Salida salida = (Salida) movimiento;
                tipo = "SALIDA";
                fecha = salida.getFecha();
                hora = salida.getHora();
                detalles = "Empleado: " + salida.getEmpleado().getNombre();
                if (!salida.getNota().isEmpty()) {
                    detalles += " - Notas: " + salida.getNota();
                }
                
                // Agregar tiempo en parking con manejo de error
                try {
                    // Verificar que la entrada no sea nula
                    if (salida.getEntrada() != null) {
                        detalles += " - Tiempo en parking: " + 
                                sistema.calcularDiferenciaTiempo(
                                    salida.getEntrada().getFecha(),
                                    salida.getEntrada().getHora(),
                                    salida.getFecha(),
                                    salida.getHora());
                    }
                } catch (Exception e) {
                    detalles += " - Tiempo en parking: No disponible";
                    System.err.println("Error al calcular tiempo en parking: " + e.getMessage());
                }
            } else if (movimiento instanceof ServicioAdicional) {
                ServicioAdicional servicio = (ServicioAdicional) movimiento;
                tipo = "SERVICIO";
                fecha = servicio.getFecha();
                hora = servicio.getHora();
                detalles = servicio.getTipoServicio() + " $" + servicio.getCostoServicio() 
                        + " Empleado: " + servicio.getEmpleado().getNombre();
            }
            
            modelo.addRow(new Object[]{tipo, fecha, hora, detalles});
        }
    }
    
    private void jRadioButtonFechaHoraDecrecienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFechaHoraDecrecienteActionPerformed
        if (matricula != null) {
            actualizarTabla();
        }
    }//GEN-LAST:event_jRadioButtonFechaHoraDecrecienteActionPerformed

    private void jRadioButtonFechaHoraCrecienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFechaHoraCrecienteActionPerformed
        if (matricula != null) {
            actualizarTabla();
        }
    }//GEN-LAST:event_jRadioButtonFechaHoraCrecienteActionPerformed

    private void jCheckBoxEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEntradasActionPerformed
        if (matricula != null) {
            actualizarTabla();
        }
    }//GEN-LAST:event_jCheckBoxEntradasActionPerformed

    private void jCheckBoxSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSalidasActionPerformed
        if (matricula != null) {
            actualizarTabla();
        }
    }//GEN-LAST:event_jCheckBoxSalidasActionPerformed

    private void jCheckBoxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxServiciosActionPerformed
        if (matricula != null) {
            actualizarTabla();
        }
    }//GEN-LAST:event_jCheckBoxServiciosActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        if (matricula != null && movimientosActuales != null && !movimientosActuales.isEmpty()) {
            sistema.exportarMovimientosATxt(movimientosActuales, matricula);
            ClaroOscuro.mostrarMensaje(this, "Archivo " + matricula + ".txt generado con éxito", "Exportación Exitosa");
        } else {
            ClaroOscuro.mostrarError(this, "No hay datos para exportar", "Error");
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonHora1Dia1;
    private javax.swing.JButton jButtonHora1Dia2;
    private javax.swing.JButton jButtonHora1Dia3;
    private javax.swing.JButton jButtonHora2Dia1;
    private javax.swing.JButton jButtonHora2Dia2;
    private javax.swing.JButton jButtonHora2Dia3;
    private javax.swing.JButton jButtonHora3Dia1;
    private javax.swing.JButton jButtonHora3Dia2;
    private javax.swing.JButton jButtonHora3Dia3;
    private javax.swing.JButton jButtonHora4Dia1;
    private javax.swing.JButton jButtonHora4Dia2;
    private javax.swing.JButton jButtonHora4Dia3;
    private javax.swing.JCheckBox jCheckBoxEntradas;
    private javax.swing.JCheckBox jCheckBoxSalidas;
    private javax.swing.JCheckBox jCheckBoxServicios;
    private javax.swing.JLabel jLabelClientesConMasVehiculos;
    private javax.swing.JLabel jLabelDia1;
    private javax.swing.JLabel jLabelDia2;
    private javax.swing.JLabel jLabelDia3;
    private javax.swing.JLabel jLabelEmpleadosConMenosMovimientos;
    private javax.swing.JLabel jLabelEstadia;
    private javax.swing.JLabel jLabelEstadiaMasLarga;
    private javax.swing.JLabel jLabelFiltrar;
    private javax.swing.JLabel jLabelHora0a6;
    private javax.swing.JLabel jLabelHora12a18;
    private javax.swing.JLabel jLabelHora18a00;
    private javax.swing.JLabel jLabelHora6a12;
    private javax.swing.JLabel jLabelListaDeVehiculos;
    private javax.swing.JLabel jLabelMovimientosDelVehiculo;
    private javax.swing.JLabel jLabelSeleccionFecha;
    private javax.swing.JLabel jLabelServiciosMasUtilizados;
    private javax.swing.JList<String> jListClientesConMasVehiculos;
    private javax.swing.JList<String> jListEmpleadosConMenosMovimientos;
    private javax.swing.JList<String> jListServiciosMasUtilizados;
    private javax.swing.JList<String> jListVehiculos;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelEstadisticas;
    private javax.swing.JPanel jPanelHistorial;
    private javax.swing.JPanel jPanelMovimientos;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JRadioButton jRadioButtonFechaHoraCreciente;
    private javax.swing.JRadioButton jRadioButtonFechaHoraDecreciente;
    private javax.swing.JScrollPane jScrollPaneClientesConMasVehiculos;
    private javax.swing.JScrollPane jScrollPaneEmpleadosConMenosMovimientos;
    private javax.swing.JScrollPane jScrollPaneServiciosMasUtilizados;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JTabbedPane jTabbedPaneReportes;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldFecha;
    // End of variables declaration//GEN-END:variables
}
