/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaGestionVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionVehiculos
     */
    public VentanaGestionVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionVehiculos = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        jListVehiculos = new javax.swing.JList<>();
        jLabelVehiculos = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jButtonVaciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Vehículos");
        getContentPane().setLayout(null);

        jPanelGestionVehiculos.setLayout(null);

        jButtonEliminar.setText("Eliminar");
        jPanelGestionVehiculos.add(jButtonEliminar);
        jButtonEliminar.setBounds(317, 270, 130, 27);

        jButtonAgregar.setText("Agregar");
        jPanelGestionVehiculos.add(jButtonAgregar);
        jButtonAgregar.setBounds(169, 270, 130, 27);

        jListVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneVehiculos.setViewportView(jListVehiculos);

        jPanelGestionVehiculos.add(jScrollPaneVehiculos);
        jScrollPaneVehiculos.setBounds(380, 90, 100, 140);

        jLabelVehiculos.setText("Vehículos");
        jPanelGestionVehiculos.add(jLabelVehiculos);
        jLabelVehiculos.setBounds(380, 60, 60, 16);

        jLabelMarca.setText("Marca");
        jPanelGestionVehiculos.add(jLabelMarca);
        jLabelMarca.setBounds(40, 70, 33, 16);

        jLabelMatricula.setText("Matrícula");
        jPanelGestionVehiculos.add(jLabelMatricula);
        jLabelMatricula.setBounds(40, 130, 50, 16);

        jLabelEstado.setText("Estado");
        jPanelGestionVehiculos.add(jLabelEstado);
        jLabelEstado.setBounds(40, 180, 50, 16);

        jLabelModelo.setText("Modelo");
        jPanelGestionVehiculos.add(jLabelModelo);
        jLabelModelo.setBounds(220, 70, 60, 16);
        jPanelGestionVehiculos.add(jTextFieldMarca);
        jTextFieldMarca.setBounds(110, 70, 75, 26);
        jPanelGestionVehiculos.add(jTextFieldModelo);
        jTextFieldModelo.setBounds(290, 70, 68, 26);
        jPanelGestionVehiculos.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(110, 130, 75, 26);
        jPanelGestionVehiculos.add(jTextFieldEstado);
        jTextFieldEstado.setBounds(110, 180, 250, 26);

        jButtonVaciar.setText("Vaciar");
        jPanelGestionVehiculos.add(jButtonVaciar);
        jButtonVaciar.setBounds(60, 270, 76, 27);

        getContentPane().add(jPanelGestionVehiculos);
        jPanelGestionVehiculos.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelVehiculos;
    private javax.swing.JList<String> jListVehiculos;
    private javax.swing.JPanel jPanelGestionVehiculos;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
}
