/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaEntradas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEntradas
     */
    public VentanaEntradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEntradas = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        jListVehiculos = new javax.swing.JList<>();
        jLabelVehiculos = new javax.swing.JLabel();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelNotas = new javax.swing.JLabel();
        jLabelTieneContrato = new javax.swing.JLabel();
        jLabelTieneContratoRespuesta = new javax.swing.JLabel();
        jTextFieldNotas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelEntradas.setLayout(null);

        jLabelFecha.setText("Fecha");
        jPanelEntradas.add(jLabelFecha);
        jLabelFecha.setBounds(30, 70, 50, 16);

        jButtonVaciar.setText("Vaciar");
        jPanelEntradas.add(jButtonVaciar);
        jButtonVaciar.setBounds(40, 290, 90, 27);

        jButtonAgregar.setText("Agregar");
        jPanelEntradas.add(jButtonAgregar);
        jButtonAgregar.setBounds(150, 290, 170, 27);

        jButtonEliminar.setText("Eliminar");
        jPanelEntradas.add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 290, 130, 27);
        jPanelEntradas.add(jTextFieldFecha);
        jTextFieldFecha.setBounds(80, 70, 70, 26);
        jPanelEntradas.add(jTextFieldHora);
        jTextFieldHora.setBounds(80, 110, 68, 26);

        jLabelHora.setText("Hora");
        jPanelEntradas.add(jLabelHora);
        jLabelHora.setBounds(30, 110, 50, 16);

        jListVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneVehiculos.setViewportView(jListVehiculos);

        jPanelEntradas.add(jScrollPaneVehiculos);
        jScrollPaneVehiculos.setBounds(260, 100, 100, 150);

        jLabelVehiculos.setText("Vehiculos");
        jPanelEntradas.add(jLabelVehiculos);
        jLabelVehiculos.setBounds(270, 70, 60, 16);

        jListEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleados.setViewportView(jListEmpleados);

        jPanelEntradas.add(jScrollPaneEmpleados);
        jScrollPaneEmpleados.setBounds(380, 100, 100, 150);

        jLabelEmpleados.setText("Empleados");
        jPanelEntradas.add(jLabelEmpleados);
        jLabelEmpleados.setBounds(390, 70, 60, 16);

        jLabelNotas.setText("Notas");
        jPanelEntradas.add(jLabelNotas);
        jLabelNotas.setBounds(30, 150, 50, 16);

        jLabelTieneContrato.setText("Tiene Contrato:");
        jPanelEntradas.add(jLabelTieneContrato);
        jLabelTieneContrato.setBounds(30, 230, 90, 16);

        jLabelTieneContratoRespuesta.setText("---");
        jPanelEntradas.add(jLabelTieneContratoRespuesta);
        jLabelTieneContratoRespuesta.setBounds(120, 230, 14, 16);
        jPanelEntradas.add(jTextFieldNotas);
        jTextFieldNotas.setBounds(80, 150, 68, 26);

        getContentPane().add(jPanelEntradas);
        jPanelEntradas.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNotas;
    private javax.swing.JLabel jLabelTieneContrato;
    private javax.swing.JLabel jLabelTieneContratoRespuesta;
    private javax.swing.JLabel jLabelVehiculos;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JList<String> jListVehiculos;
    private javax.swing.JPanel jPanelEntradas;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldNotas;
    // End of variables declaration//GEN-END:variables
}
