/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaSalidas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSalidas
     */
    public VentanaSalidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalidas = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jScrollPaneEntradas = new javax.swing.JScrollPane();
        jListEntradas = new javax.swing.JList<>();
        jLabelEntradas = new javax.swing.JLabel();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelNotas = new javax.swing.JLabel();
        jLabelTiempoEnParking = new javax.swing.JLabel();
        jLabelTiempoEnParkingResultado = new javax.swing.JLabel();
        jTextFieldNotas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelSalidas.setLayout(null);

        jLabelFecha.setText("Fecha");
        jPanelSalidas.add(jLabelFecha);
        jLabelFecha.setBounds(30, 70, 50, 16);

        jButtonVaciar.setText("Vaciar");
        jPanelSalidas.add(jButtonVaciar);
        jButtonVaciar.setBounds(40, 290, 90, 27);

        jButtonAgregar.setText("Agregar");
        jPanelSalidas.add(jButtonAgregar);
        jButtonAgregar.setBounds(150, 290, 170, 27);

        jButtonEliminar.setText("Eliminar");
        jPanelSalidas.add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 290, 130, 27);
        jPanelSalidas.add(jTextFieldFecha);
        jTextFieldFecha.setBounds(80, 70, 70, 26);
        jPanelSalidas.add(jTextFieldHora);
        jTextFieldHora.setBounds(80, 110, 68, 26);

        jLabelHora.setText("Hora");
        jPanelSalidas.add(jLabelHora);
        jLabelHora.setBounds(30, 110, 50, 16);

        jListEntradas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEntradas.setViewportView(jListEntradas);

        jPanelSalidas.add(jScrollPaneEntradas);
        jScrollPaneEntradas.setBounds(260, 100, 100, 150);

        jLabelEntradas.setText("Entradas");
        jPanelSalidas.add(jLabelEntradas);
        jLabelEntradas.setBounds(270, 70, 60, 16);

        jListEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleados.setViewportView(jListEmpleados);

        jPanelSalidas.add(jScrollPaneEmpleados);
        jScrollPaneEmpleados.setBounds(380, 100, 100, 150);

        jLabelEmpleados.setText("Empleados");
        jPanelSalidas.add(jLabelEmpleados);
        jLabelEmpleados.setBounds(390, 70, 60, 16);

        jLabelNotas.setText("Notas");
        jPanelSalidas.add(jLabelNotas);
        jLabelNotas.setBounds(30, 150, 50, 16);

        jLabelTiempoEnParking.setText("Tiempo en Parking:");
        jPanelSalidas.add(jLabelTiempoEnParking);
        jLabelTiempoEnParking.setBounds(30, 230, 110, 16);

        jLabelTiempoEnParkingResultado.setText("---");
        jPanelSalidas.add(jLabelTiempoEnParkingResultado);
        jLabelTiempoEnParkingResultado.setBounds(140, 230, 15, 16);
        jPanelSalidas.add(jTextFieldNotas);
        jTextFieldNotas.setBounds(80, 150, 68, 26);

        getContentPane().add(jPanelSalidas);
        jPanelSalidas.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelEntradas;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNotas;
    private javax.swing.JLabel jLabelTiempoEnParking;
    private javax.swing.JLabel jLabelTiempoEnParkingResultado;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JList<String> jListEntradas;
    private javax.swing.JPanel jPanelSalidas;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JScrollPane jScrollPaneEntradas;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldHora;
    private javax.swing.JTextField jTextFieldNotas;
    // End of variables declaration//GEN-END:variables
}
