/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaMiniJuego extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMiniJuego
     */
    public VentanaMiniJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMiniJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MiniJuego");
        getContentPane().setLayout(null);

        jPanelMiniJuego.setLayout(null);

        jLabel1.setText("MiniJuego");
        jPanelMiniJuego.add(jLabel1);
        jLabel1.setBounds(190, 170, 70, 16);

        getContentPane().add(jPanelMiniJuego);
        jPanelMiniJuego.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelMiniJuego;
    // End of variables declaration//GEN-END:variables
}
