/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

import java.util.ArrayList;
import model.Empleado;
import model.Sistema;

public class VentanaGestionEmpleados extends javax.swing.JFrame {

    private Sistema sistema;
    
    public VentanaGestionEmpleados(Sistema sistema) {
        this.sistema = sistema;
        
        initComponents();
        actualizarVista();
        
        ClaroOscuro.aplicarModo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionEmpleados = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNumEmpleado = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCedula = new javax.swing.JTextField();
        jTextFieldNumEmpleado = new javax.swing.JTextField();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList();

        jLabelClientes1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Empleados");
        getContentPane().setLayout(null);

        jListEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEmpleadosValueChanged(evt);
            }
        });

        jPanelGestionEmpleados.setLayout(null);

        jLabelNombre.setText("Nombre:");
        jPanelGestionEmpleados.add(jLabelNombre);
        jLabelNombre.setBounds(10, 40, 60, 16);

        jLabelDireccion.setText("Direccion:");
        jPanelGestionEmpleados.add(jLabelDireccion);
        jLabelDireccion.setBounds(10, 120, 60, 16);

        jLabelCedula.setText("Cédula:");
        jPanelGestionEmpleados.add(jLabelCedula);
        jLabelCedula.setBounds(10, 80, 50, 16);

        jLabelNumEmpleado.setText("N° Empleado:");
        jPanelGestionEmpleados.add(jLabelNumEmpleado);
        jLabelNumEmpleado.setBounds(10, 160, 80, 16);

        jLabelClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes.setText("Datos del Empleado");
        jPanelGestionEmpleados.add(jLabelClientes);
        jLabelClientes.setBounds(10, 10, 130, 16);

        jButtonVaciar.setText("Vaciar");
        jButtonVaciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaciarActionPerformed(evt);
            }
        });
        jPanelGestionEmpleados.add(jButtonVaciar);
        jButtonVaciar.setBounds(10, 250, 120, 27);

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanelGestionEmpleados.add(jButtonAgregar);
        jButtonAgregar.setBounds(130, 250, 240, 27);
        jPanelGestionEmpleados.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(100, 40, 160, 26);
        jPanelGestionEmpleados.add(jTextFieldDireccion);
        jTextFieldDireccion.setBounds(100, 120, 160, 26);
        jPanelGestionEmpleados.add(jTextFieldCedula);
        jTextFieldCedula.setBounds(100, 80, 160, 26);
        jPanelGestionEmpleados.add(jTextFieldNumEmpleado);
        jTextFieldNumEmpleado.setBounds(100, 160, 160, 26);

        jListEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleados.setViewportView(jListEmpleados);

        jPanelGestionEmpleados.add(jScrollPaneEmpleados);
        jScrollPaneEmpleados.setBounds(380, 40, 180, 240);

        jLabelClientes1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelClientes1.setText("Lista de Empleados");
        jPanelGestionEmpleados.add(jLabelClientes1);
        jLabelClientes1.setBounds(380, 10, 110, 16);

        getContentPane().add(jPanelGestionEmpleados);
        jPanelGestionEmpleados.setBounds(0, 0, 570, 320);

        setBounds(0, 0, 584, 329);
    }// </editor-fold>//GEN-END:initComponents

    private void jListEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEmpleadosValueChanged
        if (!evt.getValueIsAdjusting()) {
            mostrarEmpleadoSeleccionado();
        }
    }//GEN-LAST:event_jListEmpleadosValueChanged

    private void mostrarEmpleadoSeleccionado() {
        Empleado empleado = (Empleado) jListEmpleados.getSelectedValue();

        if (empleado != null) {
            try {
                jTextFieldNombre.setText(empleado.getNombre());
                jTextFieldCedula.setText(String.valueOf(empleado.getCedula()));
                jTextFieldDireccion.setText(empleado.getDireccion());
                jTextFieldNumEmpleado.setText(String.valueOf(empleado.getNumEmpleado()));
            } catch (Exception e) {
                ClaroOscuro.mostrarError(this, "Error al cargar datos del empleado: " + e.getMessage(),
                        "Error");
            }
        }
    }
    
    private void limpiarCampos(){
        jTextFieldNombre.setText("");
        jTextFieldCedula.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldNumEmpleado.setText("");
    }
    
    private void actualizarListaEmpleados(){
        ArrayList<Empleado> empleados = sistema.getListaEmpleados();
        jListEmpleados.setListData(empleados.toArray());
    }

    private void actualizarVista(){
        actualizarListaEmpleados();
    }
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        
        try {
            String nombre = jTextFieldNombre.getText();
            String cedulaStr = jTextFieldCedula.getText();
            String direccion = jTextFieldDireccion.getText();
            String numEmpleadoStr = jTextFieldNumEmpleado.getText();

            // Validar que los campos no estén vacíos
            if (nombre == null || nombre.trim().isEmpty()) {
                throw new Exception("El nombre no puede estar vacío");
            } 
            if (direccion == null || direccion.trim().isEmpty()) {
                throw new Exception("La dirección no puede estar vacía");
            } 
            if (cedulaStr == null || cedulaStr.trim().isEmpty()) {
                throw new Exception("La cédula no puede estar vacía");
            } 
            if (numEmpleadoStr == null || numEmpleadoStr.trim().isEmpty()) {
                throw new Exception("El número de empleado no puede estar vacío");
            } 
            
            // Convertir strings a números
            int cedula;
            int numEmpleado;
            
            try {
                cedula = Integer.parseInt(cedulaStr);
            } catch (NumberFormatException e){
                throw new Exception("La cédula debe ser un número válido");
            }
            try {
                numEmpleado = Integer.parseInt(numEmpleadoStr);
            } catch (NumberFormatException e){
                throw new Exception("El número de empleado debe ser un número válido");
            }
            
            // Validar valores numéricos
            if (cedula <= 0) {
                throw new Exception("La cédula debe ser un número positivo");
            }
            if (numEmpleado <= 0) {
                throw new Exception("El número de empleado debe ser un número positivo");
            }
            
            // Verificar unicidad
            if (sistema.existeEmpleadoConCedula(cedula)) {
                throw new Exception("Ya existe un empleado con esa cédula");
            }
            
            // Crear y registrar cliente
            Empleado empleado = new Empleado(nombre, cedula, direccion, numEmpleado);
            boolean resultado = sistema.registrarEmpleado(empleado);
            
            if (!resultado) {
                throw new Exception("No se pudo registrar el empleado");
            }

            actualizarListaEmpleados();

            ClaroOscuro.mostrarMensaje(this, "Empleado agregado con éxito", "Éxito");

            limpiarCampos();

        } catch (Exception e) {
            ClaroOscuro.mostrarError(this, e.getMessage(), "Error");
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarActionPerformed
        limpiarCampos();
        jListEmpleados.clearSelection();
    }//GEN-LAST:event_jButtonVaciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelClientes1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumEmpleado;
    private javax.swing.JList jListEmpleados;
    private javax.swing.JPanel jPanelGestionEmpleados;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumEmpleado;
    //GEN-END:variables
}
