/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */

package view;

public class VentanaInfoAutores extends javax.swing.JFrame {

     /**
     * Creates new form VentanaInfoAutores
     */
    public VentanaInfoAutores() {
        initComponents();

        ClaroOscuro.aplicarModo(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoAutores = new javax.swing.JPanel();
        jLabelMatiasPiedra = new javax.swing.JLabel();
        jLabelJoaquinPiedra = new javax.swing.JLabel();
        jLabelAutoresTitulo = new javax.swing.JLabel();
        jLabelMatiasImage = new javax.swing.JLabel();
        jLabelJoaquinImage = new javax.swing.JLabel();
        jLabelMatiasPiedraNumero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información de Autores");
        getContentPane().setLayout(null);

        jPanelInfoAutores.setLayout(null);

        jLabelMatiasPiedra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMatiasPiedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMatiasPiedra.setText("Matias Piedra");
        jPanelInfoAutores.add(jLabelMatiasPiedra);
        jLabelMatiasPiedra.setBounds(70, 230, 120, 30);

        jLabelJoaquinPiedra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelJoaquinPiedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJoaquinPiedra.setText("Joaquín Piedra ");
        jPanelInfoAutores.add(jLabelJoaquinPiedra);
        jLabelJoaquinPiedra.setBounds(290, 230, 120, 30);

        jLabelAutoresTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabelAutoresTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutoresTitulo.setText("Autores del proyecto");
        jLabelAutoresTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelAutoresTitulo.setInheritsPopupMenu(false);
        jPanelInfoAutores.add(jLabelAutoresTitulo);
        jLabelAutoresTitulo.setBounds(100, 10, 280, 60);

        jLabelMatiasImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMatiasImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/matias_image.png"))); // NOI18N
        jPanelInfoAutores.add(jLabelMatiasImage);
        jLabelMatiasImage.setBounds(70, 90, 120, 120);

        jLabelJoaquinImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJoaquinImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/joaquin_image.png"))); // NOI18N
        jPanelInfoAutores.add(jLabelJoaquinImage);
        jLabelJoaquinImage.setBounds(290, 90, 120, 120);

        jLabelMatiasPiedraNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMatiasPiedraNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMatiasPiedraNumero.setText("354007");
        jPanelInfoAutores.add(jLabelMatiasPiedraNumero);
        jLabelMatiasPiedraNumero.setBounds(70, 260, 120, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("304804");
        jPanelInfoAutores.add(jLabel1);
        jLabel1.setBounds(290, 260, 120, 30);

        getContentPane().add(jPanelInfoAutores);
        jPanelInfoAutores.setBounds(0, 0, 510, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutoresTitulo;
    private javax.swing.JLabel jLabelJoaquinImage;
    private javax.swing.JLabel jLabelJoaquinPiedra;
    private javax.swing.JLabel jLabelMatiasImage;
    private javax.swing.JLabel jLabelMatiasPiedra;
    private javax.swing.JLabel jLabelMatiasPiedraNumero;
    private javax.swing.JPanel jPanelInfoAutores;
    // End of variables declaration//GEN-END:variables
}
