/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaInfoAutores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInfoAutores
     */
    public VentanaInfoAutores() {
        initComponents();

        ClaroOscuro.aplicarModo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoAutores = new javax.swing.JPanel();
        jLabelMatiasPiedra = new javax.swing.JLabel();
        jLabelJoaquinPiedra = new javax.swing.JLabel();
        jLabelAutoresTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información de Autores");
        getContentPane().setLayout(null);

        jPanelInfoAutores.setLayout(null);

        jLabelMatiasPiedra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMatiasPiedra.setText("Matias Piedra - 354007");
        jPanelInfoAutores.add(jLabelMatiasPiedra);
        jLabelMatiasPiedra.setBounds(50, 110, 180, 30);

        jLabelJoaquinPiedra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelJoaquinPiedra.setText("Joaquín Piedra - 304804");
        jPanelInfoAutores.add(jLabelJoaquinPiedra);
        jLabelJoaquinPiedra.setBounds(50, 140, 180, 30);

        jLabelAutoresTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabelAutoresTitulo.setText("Autores del proyecto");
        jPanelInfoAutores.add(jLabelAutoresTitulo);
        jLabelAutoresTitulo.setBounds(50, 50, 280, 60);

        getContentPane().add(jPanelInfoAutores);
        jPanelInfoAutores.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAutoresTitulo;
    private javax.swing.JLabel jLabelJoaquinPiedra;
    private javax.swing.JLabel jLabelMatiasPiedra;
    private javax.swing.JPanel jPanelInfoAutores;
    // End of variables declaration//GEN-END:variables
}
