/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaInfoAutores extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInfoAutores
     */
    public VentanaInfoAutores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoAutores = new javax.swing.JPanel();
        jLabelMatiasPiedra = new javax.swing.JLabel();
        jLabel354007 = new javax.swing.JLabel();
        jLabelJoaquinPiedra = new javax.swing.JLabel();
        jLabel304804 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Información de Autores");
        getContentPane().setLayout(null);

        jPanelInfoAutores.setLayout(null);

        jLabelMatiasPiedra.setText("Matias Piedra");
        jPanelInfoAutores.add(jLabelMatiasPiedra);
        jLabelMatiasPiedra.setBounds(110, 190, 80, 16);

        jLabel354007.setText("354007");
        jPanelInfoAutores.add(jLabel354007);
        jLabel354007.setBounds(120, 220, 50, 16);

        jLabelJoaquinPiedra.setText("Joaquín Piedra");
        jPanelInfoAutores.add(jLabelJoaquinPiedra);
        jLabelJoaquinPiedra.setBounds(290, 190, 80, 16);

        jLabel304804.setText("304804");
        jPanelInfoAutores.add(jLabel304804);
        jLabel304804.setBounds(300, 220, 50, 16);

        getContentPane().add(jPanelInfoAutores);
        jPanelInfoAutores.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel304804;
    private javax.swing.JLabel jLabel354007;
    private javax.swing.JLabel jLabelJoaquinPiedra;
    private javax.swing.JLabel jLabelMatiasPiedra;
    private javax.swing.JPanel jPanelInfoAutores;
    // End of variables declaration//GEN-END:variables
}
