/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

public class VentanaReportes extends javax.swing.JFrame {

    public VentanaReportes() {
        initComponents();

        ClaroOscuro.aplicarModo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelReportes = new javax.swing.JPanel();
        jTabbedPaneReportes = new javax.swing.JTabbedPane();
        jPanelHistorial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelMovimientos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelEstadisticas = new javax.swing.JPanel();
        jLabelServiciosMasUtilizados = new javax.swing.JLabel();
        jScrollPaneServiciosMasUtilizados = new javax.swing.JScrollPane();
        jListServiciosMasUtilizados = new javax.swing.JList<>();
        jLabelEmpleadosConMenosMovimientos = new javax.swing.JLabel();
        jScrollPaneEmpleadosConMenosMovimientos = new javax.swing.JScrollPane();
        jListEmpleadosConMenosMovimientos = new javax.swing.JList<>();
        jLabelEstadiaMasLarga = new javax.swing.JLabel();
        jLabelClientesConMasVehiculos = new javax.swing.JLabel();
        jScrollPaneClientesConMasVehiculos = new javax.swing.JScrollPane();
        jListClientesConMasVehiculos = new javax.swing.JList<>();
        jLabelEstadia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        getContentPane().setLayout(null);

        jPanelReportes.setLayout(null);

        jPanelHistorial.setLayout(null);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanelHistorial.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 100, 150);

        jLabel13.setText("Lista de vehículos:");
        jPanelHistorial.add(jLabel13);
        jLabel13.setBounds(30, 20, 120, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanelHistorial.add(jScrollPane2);
        jScrollPane2.setBounds(170, 30, 320, 170);

        jTabbedPaneReportes.addTab("Historial", jPanelHistorial);

        jPanelMovimientos.setLayout(new java.awt.GridLayout(4, 3));

        jLabel1.setText("jLabel1");
        jPanelMovimientos.add(jLabel1);

        jLabel2.setText("jLabel2");
        jPanelMovimientos.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanelMovimientos.add(jLabel3);

        jLabel4.setText("jLabel4");
        jPanelMovimientos.add(jLabel4);

        jLabel5.setText("jLabel5");
        jPanelMovimientos.add(jLabel5);

        jLabel6.setText("jLabel6");
        jPanelMovimientos.add(jLabel6);

        jLabel7.setText("jLabel7");
        jPanelMovimientos.add(jLabel7);

        jLabel8.setText("jLabel8");
        jPanelMovimientos.add(jLabel8);

        jLabel9.setText("jLabel9");
        jPanelMovimientos.add(jLabel9);

        jLabel10.setText("jLabel10");
        jPanelMovimientos.add(jLabel10);

        jLabel11.setText("jLabel11");
        jPanelMovimientos.add(jLabel11);

        jLabel12.setText("jLabel12");
        jPanelMovimientos.add(jLabel12);

        jTabbedPaneReportes.addTab("Movimientos", jPanelMovimientos);

        jPanelEstadisticas.setLayout(null);

        jLabelServiciosMasUtilizados.setText("Servicios más utilizados:");
        jPanelEstadisticas.add(jLabelServiciosMasUtilizados);
        jLabelServiciosMasUtilizados.setBounds(0, 40, 150, 16);

        jListServiciosMasUtilizados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneServiciosMasUtilizados.setViewportView(jListServiciosMasUtilizados);

        jPanelEstadisticas.add(jScrollPaneServiciosMasUtilizados);
        jScrollPaneServiciosMasUtilizados.setBounds(0, 60, 120, 100);

        jLabelEmpleadosConMenosMovimientos.setText("Empleados con menos movimientos:");
        jPanelEstadisticas.add(jLabelEmpleadosConMenosMovimientos);
        jLabelEmpleadosConMenosMovimientos.setBounds(160, 40, 210, 16);

        jListEmpleadosConMenosMovimientos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleadosConMenosMovimientos.setViewportView(jListEmpleadosConMenosMovimientos);

        jPanelEstadisticas.add(jScrollPaneEmpleadosConMenosMovimientos);
        jScrollPaneEmpleadosConMenosMovimientos.setBounds(160, 60, 120, 100);

        jLabelEstadiaMasLarga.setText("Estadía más larga:");
        jPanelEstadisticas.add(jLabelEstadiaMasLarga);
        jLabelEstadiaMasLarga.setBounds(0, 180, 110, 16);

        jLabelClientesConMasVehiculos.setText("Clientes con más vehículos:");
        jPanelEstadisticas.add(jLabelClientesConMasVehiculos);
        jLabelClientesConMasVehiculos.setBounds(400, 40, 150, 16);

        jListClientesConMasVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneClientesConMasVehiculos.setViewportView(jListClientesConMasVehiculos);

        jPanelEstadisticas.add(jScrollPaneClientesConMasVehiculos);
        jScrollPaneClientesConMasVehiculos.setBounds(400, 60, 120, 100);

        jLabelEstadia.setText("Ninguna estadía");
        jPanelEstadisticas.add(jLabelEstadia);
        jLabelEstadia.setBounds(110, 180, 100, 16);

        jTabbedPaneReportes.addTab("Estadísticas Generales", jPanelEstadisticas);

        jPanelReportes.add(jTabbedPaneReportes);
        jTabbedPaneReportes.setBounds(40, 50, 730, 270);

        getContentPane().add(jPanelReportes);
        jPanelReportes.setBounds(0, 0, 650, 350);

        setBounds(0, 0, 814, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientesConMasVehiculos;
    private javax.swing.JLabel jLabelEmpleadosConMenosMovimientos;
    private javax.swing.JLabel jLabelEstadia;
    private javax.swing.JLabel jLabelEstadiaMasLarga;
    private javax.swing.JLabel jLabelServiciosMasUtilizados;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListClientesConMasVehiculos;
    private javax.swing.JList<String> jListEmpleadosConMenosMovimientos;
    private javax.swing.JList<String> jListServiciosMasUtilizados;
    private javax.swing.JPanel jPanelEstadisticas;
    private javax.swing.JPanel jPanelHistorial;
    private javax.swing.JPanel jPanelMovimientos;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneClientesConMasVehiculos;
    private javax.swing.JScrollPane jScrollPaneEmpleadosConMenosMovimientos;
    private javax.swing.JScrollPane jScrollPaneServiciosMasUtilizados;
    private javax.swing.JTabbedPane jTabbedPaneReportes;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
