/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        ClaroOscuro.aplicarModo(this);
        ClaroOscuro.aplicarModoABoton(jButtonClaroOscuro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jButtonClaroOscuro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestion = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        jMenuItemContratos = new javax.swing.JMenuItem();
        jMenuMovimientos = new javax.swing.JMenu();
        jMenuItemEntradas = new javax.swing.JMenuItem();
        jMenuItemSalidas = new javax.swing.JMenuItem();
        jMenuItemServicios = new javax.swing.JMenuItem();
        jMenuVarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuTerminar = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PARKING - Matias Piedra 354007 y Joaquin Piedra 304804");
        getContentPane().setLayout(null);

        jPanelMain.setLayout(null);
        getContentPane().add(jPanelMain);
        jPanelMain.setBounds(6, 304, 446, 0);

        jButtonClaroOscuro.setText("Claro/Oscuro");
        jButtonClaroOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClaroOscuroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClaroOscuro);
        jButtonClaroOscuro.setBounds(30, 230, 120, 27);

        jMenuGestion.setText("Gestión");

        jMenuItemClientes.setText("Gestión de Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemClientes);

        jMenuItemVehiculos.setText("Gestión de Vehículos");
        jMenuGestion.add(jMenuItemVehiculos);

        jMenuItemEmpleados.setText("Gestión de Empleados");
        jMenuGestion.add(jMenuItemEmpleados);

        jMenuItemContratos.setText("Gestión de Contratos");
        jMenuGestion.add(jMenuItemContratos);

        jMenuBar1.add(jMenuGestion);

        jMenuMovimientos.setText("Movimientos");

        jMenuItemEntradas.setText("Entradas");
        jMenuMovimientos.add(jMenuItemEntradas);

        jMenuItemSalidas.setText("Salidas");
        jMenuMovimientos.add(jMenuItemSalidas);

        jMenuItemServicios.setText("Servicios Adicionales");
        jMenuMovimientos.add(jMenuItemServicios);

        jMenuBar1.add(jMenuMovimientos);

        jMenuVarios.setText("Varios");

        jMenuItem1.setText("Reportes");
        jMenuVarios.add(jMenuItem1);

        jMenuItem2.setText("Recuperación de Datos");
        jMenuVarios.add(jMenuItem2);

        jMenuItem3.setText("Grabación de Datos");
        jMenuVarios.add(jMenuItem3);

        jMenuItem4.setText("MiniJuego");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuVarios.add(jMenuItem4);

        jMenuItem5.setText("Información de Autores");
        jMenuVarios.add(jMenuItem5);

        jMenuBar1.add(jMenuVarios);

        jMenuTerminar.setText("Terminar");

        jMenuItemSalir.setText("Salir");
        jMenuTerminar.add(jMenuItemSalir);

        jMenuBar1.add(jMenuTerminar);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 506, 345);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClaroOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClaroOscuroActionPerformed
        // TODO add your handling code here:
        ClaroOscuro.setModo();
        ClaroOscuro.aplicarModo(this);
        ClaroOscuro.aplicarModoABoton(jButtonClaroOscuro);
    }//GEN-LAST:event_jButtonClaroOscuroActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClaroOscuro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemContratos;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenuItem jMenuItemEntradas;
    private javax.swing.JMenuItem jMenuItemSalidas;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemServicios;
    private javax.swing.JMenuItem jMenuItemVehiculos;
    private javax.swing.JMenu jMenuMovimientos;
    private javax.swing.JMenu jMenuTerminar;
    private javax.swing.JMenu jMenuVarios;
    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
}
