/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

import controlador.VehiculoControlador;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Vehiculo;

public class VentanaGestionVehiculos extends javax.swing.JFrame {

    private VehiculoControlador controlador;
    
    public VentanaGestionVehiculos(VehiculoControlador controlador) {
        this.controlador = controlador;
        
        initComponents();
        
        actualizarListaVehiculos();
        
        jButtonEliminar.setVisible(false);
        
        ClaroOscuro.aplicarModo(this);
        
        //Listener para la Lista
        jListVehiculos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    mostrarVehiculoSeleccionado();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionVehiculos = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        jListVehiculos = new javax.swing.JList<>();
        jLabelVehiculos = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldEstado = new javax.swing.JTextField();
        jButtonVaciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Vehículos");
        getContentPane().setLayout(null);

        jPanelGestionVehiculos.setLayout(null);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelGestionVehiculos.add(jButtonEliminar);
        jButtonEliminar.setBounds(317, 270, 130, 27);

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanelGestionVehiculos.add(jButtonAgregar);
        jButtonAgregar.setBounds(169, 270, 130, 27);

        jListVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneVehiculos.setViewportView(jListVehiculos);

        jPanelGestionVehiculos.add(jScrollPaneVehiculos);
        jScrollPaneVehiculos.setBounds(380, 90, 100, 140);

        jLabelVehiculos.setText("Vehículos");
        jPanelGestionVehiculos.add(jLabelVehiculos);
        jLabelVehiculos.setBounds(380, 60, 60, 16);

        jLabelMarca.setText("Marca");
        jPanelGestionVehiculos.add(jLabelMarca);
        jLabelMarca.setBounds(40, 70, 33, 16);

        jLabelMatricula.setText("Matrícula");
        jPanelGestionVehiculos.add(jLabelMatricula);
        jLabelMatricula.setBounds(40, 130, 50, 16);

        jLabelEstado.setText("Estado");
        jPanelGestionVehiculos.add(jLabelEstado);
        jLabelEstado.setBounds(40, 180, 50, 16);

        jLabelModelo.setText("Modelo");
        jPanelGestionVehiculos.add(jLabelModelo);
        jLabelModelo.setBounds(220, 70, 60, 16);
        jPanelGestionVehiculos.add(jTextFieldMarca);
        jTextFieldMarca.setBounds(110, 70, 75, 26);
        jPanelGestionVehiculos.add(jTextFieldModelo);
        jTextFieldModelo.setBounds(290, 70, 68, 26);
        jPanelGestionVehiculos.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(110, 130, 75, 26);
        jPanelGestionVehiculos.add(jTextFieldEstado);
        jTextFieldEstado.setBounds(110, 180, 250, 26);

        jButtonVaciar.setText("Vaciar");
        jButtonVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVaciarActionPerformed(evt);
            }
        });
        jPanelGestionVehiculos.add(jButtonVaciar);
        jButtonVaciar.setBounds(60, 270, 76, 27);

        getContentPane().add(jPanelGestionVehiculos);
        jPanelGestionVehiculos.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarVehiculoSeleccionado() {
        String seleccionado = jListVehiculos.getSelectedValue();

        if (seleccionado != null) {
            try {
                String matricula = seleccionado.split(" - ")[1];
                Vehiculo vehiculo = controlador.buscarVehiculoPorMatricula(matricula);

                if (vehiculo != null) {
                    jTextFieldMatricula.setText(vehiculo.getMatricula());
                    jTextFieldMarca.setText(String.valueOf(vehiculo.getMarca()));
                    jTextFieldModelo.setText(vehiculo.getModelo());
                    jTextFieldEstado.setText(vehiculo.getEstado());                }
            } catch (Exception e) {
                ClaroOscuro.mostrarError(this, "Error al cargar datos del vehículo: " + e.getMessage(),
                        "Error");
            }
        }
    }

    private void limpiarCampos() {
        jTextFieldMatricula.setText("");
        jTextFieldMarca.setText("");
        jTextFieldModelo.setText("");
        jTextFieldEstado.setText("");
    }

    private void actualizarListaVehiculos() {
        ArrayList<Vehiculo> vehiculos = controlador.getListaVehiculos();
        DefaultListModel<String> modelo = new DefaultListModel<>();

        for (int i = 0; i < vehiculos.size(); i++) {
            Vehiculo vehiculo = vehiculos.get(i);
            modelo.addElement(vehiculo.getMarca() + " " + vehiculo.getModelo() + " - " + vehiculo.getMatricula());
        }

        jListVehiculos.setModel(modelo);
    }
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        
        try {
            String matricula = jTextFieldMatricula.getText();
            String marca = jTextFieldMarca.getText();
            String modelo = jTextFieldModelo.getText();
            String estado = jTextFieldEstado.getText();

            controlador.registrarVehiculo(matricula, marca, modelo, estado);            actualizarListaVehiculos();

            ClaroOscuro.mostrarMensaje(this, "Vehículo agregado con éxito", "Éxito");

            limpiarCampos();

        } catch (Exception e) {
            ClaroOscuro.mostrarError(this, e.getMessage(), "Error");
        }
        
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        
        try {
            String seleccionado = jListVehiculos.getSelectedValue();            
            if (seleccionado == null) {
                ClaroOscuro.mostrarAdvertencia(this, "Debe seleccionar un vehículo para eliminar",
                        "Selección requerida");
                return;
            }

            String matricula = seleccionado.split(" - ")[1];

            int confirmacion = ClaroOscuro.mostrarConfirmacion(this,
                    "¿Está seguro que desea eliminar este vehículo?",
                    "Confirmar eliminación");

            if (confirmacion == JOptionPane.YES_OPTION) {
                controlador.eliminarVehiculo(matricula);

                actualizarListaVehiculos();
                ClaroOscuro.mostrarMensaje(this, "Vehículo eliminado con éxito", "Éxito");
                limpiarCampos();
            }        } catch (Exception e) {
            ClaroOscuro.mostrarError(this, e.getMessage(), "Error");
        }
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarActionPerformed
        limpiarCampos();
        jListVehiculos.clearSelection();
    }//GEN-LAST:event_jButtonVaciarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelVehiculos;
    private javax.swing.JList<String> jListVehiculos;
    private javax.swing.JPanel jPanelGestionVehiculos;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
}
