/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Entrada;
import model.Salida;
import model.ServicioAdicional;

public class VentanaMovimientos extends javax.swing.JDialog {

    private ArrayList<Object> movimientos;
    
    public VentanaMovimientos(java.awt.Frame ventanaPadre, boolean bloquear, 
            ArrayList<Object> movimientos, String fecha, String rangoHorario) {
        super(ventanaPadre, bloquear);
        initComponents();
        this.movimientos = movimientos;
        
        this.setTitle("Movimientos: " + fecha + " (" + rangoHorario + ")");
        
        iniciarTabla();
        actualizarMovimientos();
        
        ClaroOscuro.aplicarModoJDialog(this);
        
        setLocationRelativeTo(ventanaPadre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentanaMovimientos = new javax.swing.JPanel();
        jScrollPaneTablaMovimientos = new javax.swing.JScrollPane();
        jTableTablaMovimientos = new javax.swing.JTable();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanelVentanaMovimientos.setLayout(null);

        jTableTablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTablaMovimientos.setViewportView(jTableTablaMovimientos);

        jPanelVentanaMovimientos.add(jScrollPaneTablaMovimientos);
        jScrollPaneTablaMovimientos.setBounds(10, 10, 380, 210);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanelVentanaMovimientos.add(jButtonCerrar);
        jButtonCerrar.setBounds(140, 230, 120, 27);

        getContentPane().add(jPanelVentanaMovimientos);
        jPanelVentanaMovimientos.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(414, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void iniciarTabla() {
        String[] columnas = {"Tipo", "Fecha", "Hora", "Matrícula"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableTablaMovimientos.setModel(modelo);
    }
    
    private void actualizarMovimientos() {
        DefaultTableModel modelo = (DefaultTableModel) jTableTablaMovimientos.getModel();
        modelo.setRowCount(0);

        for (int i = 0; i < movimientos.size(); i++) {
            Object movimiento = movimientos.get(i);

            String tipo = "";
            String fecha = "";
            String hora = "";
            String matricula = "";

            if (movimiento instanceof Entrada) {
                Entrada entrada = (Entrada) movimiento;
                tipo = "ENTRADA";
                fecha = entrada.getFecha();
                hora = entrada.getHora();
                matricula = entrada.getVehiculo().getMatricula();
            } else if (movimiento instanceof Salida) {
                Salida salida = (Salida) movimiento;
                tipo = "SALIDA";
                fecha = salida.getFecha();
                hora = salida.getHora();
                matricula = salida.getVehiculo().getMatricula();
            } else if (movimiento instanceof ServicioAdicional) {
                ServicioAdicional servicio = (ServicioAdicional) movimiento;
                tipo = "SERVICIO";
                fecha = servicio.getFecha();
                hora = servicio.getHora();
                matricula = servicio.getVehiculo().getMatricula();
            }

            modelo.addRow(new Object[]{tipo, fecha, hora, matricula});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JPanel jPanelVentanaMovimientos;
    private javax.swing.JScrollPane jScrollPaneTablaMovimientos;
    private javax.swing.JTable jTableTablaMovimientos;
    // End of variables declaration//GEN-END:variables
}
