/**
 * Autores: [Matias Piedra 354007] y [Joaquin Piedra 304804]
 */
package view;

import controlador.ClienteControlador;
import controlador.ContratoControlador;
import controlador.EmpleadoControlador;
import controlador.EntradaControlador;
import controlador.SalidaControlador;
import controlador.ServicioAdicionalControlador;
import controlador.VehiculoControlador;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import model.ServicioAdicional;
import model.Sistema;

public class VentanaPrincipal extends javax.swing.JFrame implements PropertyChangeListener{

    private Sistema sistema;
    private ClienteControlador clienteControlador;
    private EmpleadoControlador empleadoControlador;
    private VehiculoControlador vehiculoControlador;
    private ContratoControlador contratoControlador;
    private EntradaControlador entradaControlador;
    private SalidaControlador salidaControlador;
    private ServicioAdicionalControlador servicioAdicionalControlador;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Sistema sistema) {
        this.sistema = sistema;
        this.clienteControlador = new ClienteControlador(sistema);
        this.empleadoControlador = new EmpleadoControlador(sistema);
        this.vehiculoControlador = new VehiculoControlador(sistema);
        this.contratoControlador = new ContratoControlador(sistema);
        this.entradaControlador = new EntradaControlador(sistema);
        this.salidaControlador = new SalidaControlador(sistema);
        this.servicioAdicionalControlador = new ServicioAdicionalControlador(sistema);
        
        initComponents();
        jPanelMain.setBounds(0,0, this.getWidth(), this.getHeight());
        setLocationRelativeTo(null);
        
        ClaroOscuro.aplicarModo(this);
        ClaroOscuro.addPropertyChangeListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jButtonClaroOscuro = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestion = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        jMenuItemContratos = new javax.swing.JMenuItem();
        jMenuMovimientos = new javax.swing.JMenu();
        jMenuItemEntradas = new javax.swing.JMenuItem();
        jMenuItemSalidas = new javax.swing.JMenuItem();
        jMenuItemServicios = new javax.swing.JMenuItem();
        jMenuVarios = new javax.swing.JMenu();
        jMenuItemReportes = new javax.swing.JMenuItem();
        jMenuItemRecuperacionDatos = new javax.swing.JMenuItem();
        jMenuItemGrabacionDatos = new javax.swing.JMenuItem();
        jMenuItemMiniJuego = new javax.swing.JMenuItem();
        jMenuItemInfoAutores = new javax.swing.JMenuItem();
        jMenuTerminar = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PARKING - Matias Piedra 354007 y Joaquin Piedra 304804");
        getContentPane().setLayout(null);

        jPanelMain.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMain.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(null);

        jButtonClaroOscuro.setText("Claro/Oscuro");
        jButtonClaroOscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClaroOscuroActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonClaroOscuro);
        jButtonClaroOscuro.setBounds(30, 230, 120, 27);

        getContentPane().add(jPanelMain);
        jPanelMain.setBounds(0, 0, 500, 330);

        jMenuGestion.setText("Gestión");

        jMenuItemClientes.setText("Gestión de Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemClientes);

        jMenuItemVehiculos.setText("Gestión de Vehículos");
        jMenuItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVehiculosActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemVehiculos);

        jMenuItemEmpleados.setText("Gestión de Empleados");
        jMenuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpleadosActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemEmpleados);

        jMenuItemContratos.setText("Gestión de Contratos");
        jMenuItemContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContratosActionPerformed(evt);
            }
        });
        jMenuGestion.add(jMenuItemContratos);

        jMenuBar1.add(jMenuGestion);

        jMenuMovimientos.setText("Movimientos");

        jMenuItemEntradas.setText("Entradas");
        jMenuItemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEntradasActionPerformed(evt);
            }
        });
        jMenuMovimientos.add(jMenuItemEntradas);

        jMenuItemSalidas.setText("Salidas");
        jMenuItemSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalidasActionPerformed(evt);
            }
        });
        jMenuMovimientos.add(jMenuItemSalidas);

        jMenuItemServicios.setText("Servicios Adicionales");
        jMenuItemServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemServiciosActionPerformed(evt);
            }
        });
        jMenuMovimientos.add(jMenuItemServicios);

        jMenuBar1.add(jMenuMovimientos);

        jMenuVarios.setText("Varios");

        jMenuItemReportes.setText("Reportes");
        jMenuItemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportesActionPerformed(evt);
            }
        });
        jMenuVarios.add(jMenuItemReportes);

        jMenuItemRecuperacionDatos.setText("Recuperación de Datos");
        jMenuItemRecuperacionDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecuperacionDatosActionPerformed(evt);
            }
        });
        jMenuVarios.add(jMenuItemRecuperacionDatos);

        jMenuItemGrabacionDatos.setText("Grabación de Datos");
        jMenuItemGrabacionDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrabacionDatosActionPerformed(evt);
            }
        });
        jMenuVarios.add(jMenuItemGrabacionDatos);

        jMenuItemMiniJuego.setText("MiniJuego");
        jMenuItemMiniJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMiniJuegoActionPerformed(evt);
            }
        });
        jMenuVarios.add(jMenuItemMiniJuego);

        jMenuItemInfoAutores.setText("Información de Autores");
        jMenuItemInfoAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInfoAutoresActionPerformed(evt);
            }
        });
        jMenuVarios.add(jMenuItemInfoAutores);

        jMenuBar1.add(jMenuVarios);

        jMenuTerminar.setText("Terminar");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuTerminar.add(jMenuItemSalir);

        jMenuBar1.add(jMenuTerminar);        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(514, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClaroOscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClaroOscuroActionPerformed
        // TODO add your handling code here:
        ClaroOscuro.setModo();
        ClaroOscuro.aplicarModo(this);
    }//GEN-LAST:event_jButtonClaroOscuroActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        VentanaGestionClientes ventanaClientes = new VentanaGestionClientes(clienteControlador);
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemMiniJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMiniJuegoActionPerformed
        VentanaMiniJuego ventanaMiniJuego = new VentanaMiniJuego();
        ventanaMiniJuego.setVisible(true);
    }//GEN-LAST:event_jMenuItemMiniJuegoActionPerformed

    private void jMenuItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVehiculosActionPerformed
        VentanaGestionVehiculos ventanaVehiculos = new VentanaGestionVehiculos(vehiculoControlador);
        ventanaVehiculos.setVisible(true);
    }//GEN-LAST:event_jMenuItemVehiculosActionPerformed

    private void jMenuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpleadosActionPerformed
        VentanaGestionEmpleados ventanaEmpleados = new VentanaGestionEmpleados(empleadoControlador);
        ventanaEmpleados.setVisible(true);
    }//GEN-LAST:event_jMenuItemEmpleadosActionPerformed

    private void jMenuItemContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContratosActionPerformed
        VentanaGestionContratos ventanaContratos = new VentanaGestionContratos(contratoControlador);
        ventanaContratos.setVisible(true);
    }//GEN-LAST:event_jMenuItemContratosActionPerformed

    private void jMenuItemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEntradasActionPerformed
        VentanaEntradas ventanaEntradas = new VentanaEntradas(entradaControlador);
        ventanaEntradas.setVisible(true);
    }//GEN-LAST:event_jMenuItemEntradasActionPerformed

    private void jMenuItemSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalidasActionPerformed
        VentanaSalidas ventanaSalidas = new VentanaSalidas(salidaControlador);
        ventanaSalidas.setVisible(true);
    }//GEN-LAST:event_jMenuItemSalidasActionPerformed

    private void jMenuItemServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemServiciosActionPerformed
        VentanaServiciosAdicionales ventanaServiciosAdicionales = new VentanaServiciosAdicionales(servicioAdicionalControlador);
        ventanaServiciosAdicionales.setVisible(true);
    }//GEN-LAST:event_jMenuItemServiciosActionPerformed

    private void jMenuItemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportesActionPerformed
        VentanaReportes ventanaReportes = new VentanaReportes();
        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_jMenuItemReportesActionPerformed

    private void jMenuItemInfoAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInfoAutoresActionPerformed
        VentanaInfoAutores ventanaInfoAutores = new VentanaInfoAutores();
        ventanaInfoAutores.setVisible(true);
    }//GEN-LAST:event_jMenuItemInfoAutoresActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemRecuperacionDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecuperacionDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRecuperacionDatosActionPerformed

    private void jMenuItemGrabacionDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrabacionDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGrabacionDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClaroOscuro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemContratos;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenuItem jMenuItemEntradas;
    private javax.swing.JMenuItem jMenuItemGrabacionDatos;
    private javax.swing.JMenuItem jMenuItemInfoAutores;
    private javax.swing.JMenuItem jMenuItemMiniJuego;
    private javax.swing.JMenuItem jMenuItemRecuperacionDatos;
    private javax.swing.JMenuItem jMenuItemReportes;
    private javax.swing.JMenuItem jMenuItemSalidas;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemServicios;
    private javax.swing.JMenuItem jMenuItemVehiculos;
    private javax.swing.JMenu jMenuMovimientos;
    private javax.swing.JMenu jMenuTerminar;
    private javax.swing.JMenu jMenuVarios;    private javax.swing.JPanel jPanelMain;
    // End of variables declaration//GEN-END:variables
      @Override
    public void propertyChange(PropertyChangeEvent evt) {

    }
}
