/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaGestionContratos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionContratos
     */
    public VentanaGestionContratos() {
        initComponents();

        ClaroOscuro.aplicarModo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionContratos = new javax.swing.JPanel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelContratos = new javax.swing.JLabel();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldFechaInicio = new javax.swing.JTextField();
        jScrollPaneContratos = new javax.swing.JScrollPane();
        jListContratos = new javax.swing.JList<>();
        jTextFieldValorMensual = new javax.swing.JTextField();
        jLabelValorMensual = new javax.swing.JLabel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList<>();
        jLabelClientes = new javax.swing.JLabel();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        jListVehiculos = new javax.swing.JList<>();
        jLabelVehiculos = new javax.swing.JLabel();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        jLabelEmpleados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Contratos");
        getContentPane().setLayout(null);

        jPanelGestionContratos.setLayout(null);

        jLabelFechaInicio.setText("Fecha Inicio");
        jPanelGestionContratos.add(jLabelFechaInicio);
        jLabelFechaInicio.setBounds(30, 30, 70, 16);

        jLabelContratos.setText("Contratos");
        jPanelGestionContratos.add(jLabelContratos);
        jLabelContratos.setBounds(390, 70, 60, 16);

        jButtonVaciar.setText("Vaciar");
        jPanelGestionContratos.add(jButtonVaciar);
        jButtonVaciar.setBounds(40, 290, 90, 27);

        jButtonAgregar.setText("Agregar");
        jPanelGestionContratos.add(jButtonAgregar);
        jButtonAgregar.setBounds(150, 290, 170, 27);

        jButtonEliminar.setText("Eliminar");
        jPanelGestionContratos.add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 290, 130, 27);
        jPanelGestionContratos.add(jTextFieldFechaInicio);
        jTextFieldFechaInicio.setBounds(110, 30, 70, 26);

        jListContratos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneContratos.setViewportView(jListContratos);

        jPanelGestionContratos.add(jScrollPaneContratos);
        jScrollPaneContratos.setBounds(380, 100, 100, 150);
        jPanelGestionContratos.add(jTextFieldValorMensual);
        jTextFieldValorMensual.setBounds(290, 30, 68, 26);

        jLabelValorMensual.setText("Valor Mensual");
        jPanelGestionContratos.add(jLabelValorMensual);
        jLabelValorMensual.setBounds(200, 30, 90, 16);

        jListClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneClientes.setViewportView(jListClientes);

        jPanelGestionContratos.add(jScrollPaneClientes);
        jScrollPaneClientes.setBounds(20, 100, 100, 150);

        jLabelClientes.setText("Clientes");
        jPanelGestionContratos.add(jLabelClientes);
        jLabelClientes.setBounds(30, 70, 60, 16);

        jListVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneVehiculos.setViewportView(jListVehiculos);

        jPanelGestionContratos.add(jScrollPaneVehiculos);
        jScrollPaneVehiculos.setBounds(130, 100, 100, 150);

        jLabelVehiculos.setText("Vehiculos");
        jPanelGestionContratos.add(jLabelVehiculos);
        jLabelVehiculos.setBounds(140, 70, 60, 16);

        jListEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleados.setViewportView(jListEmpleados);

        jPanelGestionContratos.add(jScrollPaneEmpleados);
        jScrollPaneEmpleados.setBounds(240, 100, 100, 150);

        jLabelEmpleados.setText("Empleados");
        jPanelGestionContratos.add(jLabelEmpleados);
        jLabelEmpleados.setBounds(250, 70, 60, 16);

        getContentPane().add(jPanelGestionContratos);
        jPanelGestionContratos.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelContratos;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelValorMensual;
    private javax.swing.JLabel jLabelVehiculos;
    private javax.swing.JList<String> jListClientes;
    private javax.swing.JList<String> jListContratos;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JList<String> jListVehiculos;
    private javax.swing.JPanel jPanelGestionContratos;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JScrollPane jScrollPaneContratos;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JTextField jTextFieldFechaInicio;
    private javax.swing.JTextField jTextFieldValorMensual;
    // End of variables declaration//GEN-END:variables
}
