/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaServiciosAdicionales extends javax.swing.JFrame {

    /**
     * Creates new form VentanaServiciosAdicionales
     */
    public VentanaServiciosAdicionales() {
        initComponents();

        ClaroOscuro.aplicarModo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelServiciosAdicionales = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldHora = new javax.swing.JTextField();
        jLabelHora = new javax.swing.JLabel();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        jListVehiculos = new javax.swing.JList<>();
        jLabelVehiculos = new javax.swing.JLabel();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        jLabelEmpleados = new javax.swing.JLabel();
        jLabelNotas = new javax.swing.JLabel();
        jComboBoxServicio = new javax.swing.JComboBox<>();
        jScrollPaneServiciosRealizadps = new javax.swing.JScrollPane();
        jListServiciosRealizados = new javax.swing.JList<>();
        jLabelServiciosRealizados = new javax.swing.JLabel();
        jLabelCosto = new javax.swing.JLabel();
        jTextFieldCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servicios Adicionales");
        getContentPane().setLayout(null);

        jPanelServiciosAdicionales.setLayout(null);

        jLabelFecha.setText("Fecha");
        jPanelServiciosAdicionales.add(jLabelFecha);
        jLabelFecha.setBounds(30, 70, 50, 16);

        jButtonVaciar.setText("Vaciar");
        jPanelServiciosAdicionales.add(jButtonVaciar);
        jButtonVaciar.setBounds(40, 290, 90, 27);

        jButtonAgregar.setText("Agregar");
        jPanelServiciosAdicionales.add(jButtonAgregar);
        jButtonAgregar.setBounds(150, 290, 170, 27);

        jButtonEliminar.setText("Eliminar");
        jPanelServiciosAdicionales.add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 290, 130, 27);
        jPanelServiciosAdicionales.add(jTextFieldFecha);
        jTextFieldFecha.setBounds(80, 70, 70, 26);
        jPanelServiciosAdicionales.add(jTextFieldHora);
        jTextFieldHora.setBounds(80, 110, 68, 26);

        jLabelHora.setText("Hora");
        jPanelServiciosAdicionales.add(jLabelHora);
        jLabelHora.setBounds(30, 110, 50, 16);

        jListVehiculos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneVehiculos.setViewportView(jListVehiculos);

        jPanelServiciosAdicionales.add(jScrollPaneVehiculos);
        jScrollPaneVehiculos.setBounds(160, 100, 100, 150);

        jLabelVehiculos.setText("Vehiculos");
        jPanelServiciosAdicionales.add(jLabelVehiculos);
        jLabelVehiculos.setBounds(170, 70, 60, 16);

        jListEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleados.setViewportView(jListEmpleados);

        jPanelServiciosAdicionales.add(jScrollPaneEmpleados);
        jScrollPaneEmpleados.setBounds(270, 100, 100, 150);

        jLabelEmpleados.setText("Empleados");
        jPanelServiciosAdicionales.add(jLabelEmpleados);
        jLabelEmpleados.setBounds(270, 70, 60, 16);

        jLabelNotas.setText("Servicio");
        jPanelServiciosAdicionales.add(jLabelNotas);
        jLabelNotas.setBounds(30, 150, 50, 16);

        jComboBoxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelServiciosAdicionales.add(jComboBoxServicio);
        jComboBoxServicio.setBounds(80, 150, 76, 26);

        jListServiciosRealizados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneServiciosRealizadps.setViewportView(jListServiciosRealizados);

        jPanelServiciosAdicionales.add(jScrollPaneServiciosRealizadps);
        jScrollPaneServiciosRealizadps.setBounds(380, 100, 100, 150);

        jLabelServiciosRealizados.setText("Servicios Realizados");
        jPanelServiciosAdicionales.add(jLabelServiciosRealizados);
        jLabelServiciosRealizados.setBounds(380, 70, 110, 16);

        jLabelCosto.setText("Costo");
        jPanelServiciosAdicionales.add(jLabelCosto);
        jLabelCosto.setBounds(30, 190, 50, 16);
        jPanelServiciosAdicionales.add(jTextFieldCosto);
        jTextFieldCosto.setBounds(80, 190, 70, 26);

        getContentPane().add(jPanelServiciosAdicionales);
        jPanelServiciosAdicionales.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JComboBox<String> jComboBoxServicio;
    private javax.swing.JLabel jLabelCosto;
    private javax.swing.JLabel jLabelEmpleados;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNotas;
    private javax.swing.JLabel jLabelServiciosRealizados;
    private javax.swing.JLabel jLabelVehiculos;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JList<String> jListServiciosRealizados;
    private javax.swing.JList<String> jListVehiculos;
    private javax.swing.JPanel jPanelServiciosAdicionales;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JScrollPane jScrollPaneServiciosRealizadps;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JTextField jTextFieldCosto;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldHora;
    // End of variables declaration//GEN-END:variables
}
