/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author matip
 */
public class VentanaGestionEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGestionEmpleados
     */
    public VentanaGestionEmpleados() {
        initComponents();

        ClaroOscuro.aplicarModo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGestionEmpleados = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNumEmpleado = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jButtonVaciar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPaneEmpleados = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Empleados");
        getContentPane().setLayout(null);

        jPanelGestionEmpleados.setLayout(null);

        jLabelNombre.setText("Nombre");
        jPanelGestionEmpleados.add(jLabelNombre);
        jLabelNombre.setBounds(37, 100, 60, 16);

        jLabelDireccion.setText("Direccion");
        jPanelGestionEmpleados.add(jLabelDireccion);
        jLabelDireccion.setBounds(37, 140, 60, 16);

        jLabelCedula.setText("Cédula");
        jPanelGestionEmpleados.add(jLabelCedula);
        jLabelCedula.setBounds(200, 100, 50, 16);

        jLabelNumEmpleado.setText("N° Empleado");
        jPanelGestionEmpleados.add(jLabelNumEmpleado);
        jLabelNumEmpleado.setBounds(200, 140, 80, 16);

        jLabelClientes.setText("Empleados");
        jPanelGestionEmpleados.add(jLabelClientes);
        jLabelClientes.setBounds(387, 50, 60, 16);

        jButtonVaciar.setText("Vaciar");
        jPanelGestionEmpleados.add(jButtonVaciar);
        jButtonVaciar.setBounds(40, 280, 90, 27);

        jButtonAgregar.setText("Agregar");
        jPanelGestionEmpleados.add(jButtonAgregar);
        jButtonAgregar.setBounds(150, 280, 170, 27);

        jButtonEliminar.setText("Eliminar");
        jPanelGestionEmpleados.add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 280, 130, 27);
        jPanelGestionEmpleados.add(jTextField1);
        jTextField1.setBounds(110, 100, 68, 26);
        jPanelGestionEmpleados.add(jTextField2);
        jTextField2.setBounds(110, 140, 68, 26);
        jPanelGestionEmpleados.add(jTextField4);
        jTextField4.setBounds(290, 100, 70, 26);
        jPanelGestionEmpleados.add(jTextField5);
        jTextField5.setBounds(290, 140, 75, 26);

        jListEmpleados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneEmpleados.setViewportView(jListEmpleados);

        jPanelGestionEmpleados.add(jScrollPaneEmpleados);
        jScrollPaneEmpleados.setBounds(380, 80, 100, 150);

        getContentPane().add(jPanelGestionEmpleados);
        jPanelGestionEmpleados.setBounds(0, 0, 500, 350);

        setBounds(0, 0, 514, 358);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonVaciar;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumEmpleado;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JPanel jPanelGestionEmpleados;
    private javax.swing.JScrollPane jScrollPaneEmpleados;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
